version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      python-requirements:
        patterns:
          - "*"

  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      poetry-dependencies:
        patterns:
          - "*" 

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
