site_name: MQPy
repo_url: https://github.com/Joaopeuko/Mql5-Python-Integration
repo_name: MQPy
nav:
  - Home: index.md
  - API Reference: reference/

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.magiclink:
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  favicon: /img/favicon.svg
  logo: /img/favicon.svg
  features:
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.sections
  - navigation.indexes
  - navigation.tracking
  - content.code.annotate
  - toc.follow
  - navigation.footer
  - navigation.top
  - content.code.copy
  - content.tabs.link
  palette:
      # Note: Using the system theme works with the insiders version
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: astral-light
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: astral-dark
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
extra_css:
  - extra.css
extra_javascript:
  - extra.js
plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]  # Look for Python modules in the current directory
          options:
            show_root_heading: false  # Don't show the module name as a heading
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_source: true
            show_bases: true
            show_signature: true
            heading_level: 2  # Start headings at level 2 (h2)
            members_order: source
            docstring_style: google
            docstring_section_style: table
            separate_signature: true
            merge_init_into_class: true
            show_submodules: false
            filters: ["!^_[^_]", "!^__init__"]  # Hide private attributes but show __init__
            show_inherited_members: false
            annotations_path: source
            docstring_options:
              ignore_init_summary: true
            line_length: 80
            show_root_members_full_path: false
            show_module_member_docstring: true
  - mkdocs-jupyter

watch:
  - mqpy  # Watch for changes in the mqpy directory
