site_name: MQPy
repo_url: https://github.com/Joaopeuko/Mql5-Python-Integration
repo_name: MQPy

# Enable GitHub repository statistics
edit_uri: ""  # Disable edit button by setting to empty string
# Settings for GitHub stars and forks display
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Joaopeuko/Mql5-Python-Integration
      name: GitHub
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  status:
    new: Recently added
    deprecated: Deprecated
  # Display GitHub stars and forks metrics
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by using
            <a href="https://github.com/Joaopeuko/Mql5-Python-Integration/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">our issue tracker</a>.

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Joaopeuko
      repo: Mql5-Python-Integration
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  favicon: assets/favicon.svg
  logo: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.tooltips
    # Enable GitHub repository statistics
    - content.action.edit
    - content.action.view
    - navigation.footer
    # Shows the GitHub icon with repository stats
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        scheme: astral-light
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: astral-dark
        toggle:
          icon: material/brightness-4
          name: Switch to system preference
extra_css:
  - extra.css
extra_javascript:
  - extra.js
plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: false
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_source: true
            show_bases: true
            show_signature: true
            heading_level: 2
            members_order: source
            docstring_style: google
            docstring_section_style: table
            separate_signature: true
            merge_init_into_class: true
            show_submodules: false
            filters: ["!^_[^_]", "!^__init__"]
            show_inherited_members: false
            annotations_path: source
            docstring_options:
              ignore_init_summary: true
            line_length: 80
            show_root_members_full_path: false
            show_module_member_docstring: true
  - mkdocs-jupyter
nav:
- Home: index.md
- Contributing: contributing.md
- Code documentation: reference/
