name: Deploy | Publish Pypi Packages

on:
  push:
    branches:
      - '**'        # All branches for Test PyPI
    tags:
      - "*"
jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel build twine

      - name: Clean dist directory
        run: |
          if (Test-Path -Path dist) { Remove-Item dist -Recurse -Force }

      - name: Extract issue number and suffix
        id: issue
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          # Look for #<number> in commit message
          $match = git log -1 --pretty=%B | Select-String -Pattern '#(\d+)'
          if ($match) {
            $num = $match.Matches.Groups[1].Value
            $suffix = "rc$num"
          } else {
            # No issue number => development build
            $suffix = 'dev0'
          }
          echo "SUFFIX=$suffix" >> $env:GITHUB_ENV
          echo "suffix=$suffix" >> $env:GITHUB_OUTPUT

      - name: Extract version from pyproject.toml
        id: version
        run: |
          $verLine = Get-Content pyproject.toml | Select-String -Pattern 'version = "(.*)"'
          $VERSION = $verLine.Matches.Groups[1].Value -replace '^v', ''
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          echo "version=$VERSION" >> $env:GITHUB_OUTPUT
          if ("${{ github.ref }}".StartsWith('refs/tags/')) {
            $TAG_VERSION = "${{ github.ref }}".Substring(10) -replace '^v', ''
            echo "TAG_VERSION=$TAG_VERSION" >> $env:GITHUB_ENV
          }

      - name: Build package
        run: |
          python -m build

      - name: Check distributions
        run: |
          twine check dist/*

      - name: Publish to Test PyPI (branch push)
        if: startsWith(github.ref, 'refs/heads/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI }}
          SUFFIX: ${{ env.SUFFIX }}
        run: |
          # Rename wheel files to include suffix
          Get-ChildItem dist/*.whl | ForEach-Object {
            Write-Host "Original wheel: $_"
            $newName = $_.Name -replace '^(mqpy-\d+\.\d+\.\d+)-', '$1.' + $env:SUFFIX + '-'
            Write-Host "Renaming to: $newName"
            Rename-Item $_.FullName $newName
          }
          # Rename source tarballs
          Get-ChildItem dist/*.tar.gz | ForEach-Object {
            Write-Host "Original tarball: $_"
            $newName = $_.Name -replace '^(mqpy-\d+\.\d+\.\d+)', '$1.' + $env:SUFFIX
            Write-Host "Renaming to: $newName"
            Rename-Item $_.FullName $newName
          }

          Write-Host "Files ready for upload:"
          Get-ChildItem dist/* | ForEach-Object { Write-Host "  $_" }

          # Upload with verbose output for debugging
          twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Publish to PyPI (new tag)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          Write-Host "Files to upload to PyPI:"
          Get-ChildItem dist/* | ForEach-Object { Write-Host "  $_" }
          twine upload --verbose dist/*

      - name: Create Step Summary
        run: |
          @"
          # MQPy Package

          ## Installation Instructions

          ### Important Warning ⚠️
          !!! warning "Trading Risk Warning"
          **IMPORTANT: Trading involves substantial risk of loss and is not suitable for all investors.**

          - Always use a **demo account** with fake money when testing strategies
          - MQPy is provided for **educational purposes only**
          - Past performance is not indicative of future results
          - Never trade with money you cannot afford to lose
          - The developers are not responsible for any financial losses

          ### Windows-Only Compatibility
          This package is designed to work exclusively on Windows operating systems.

          ### Installation Steps

          $( if ("${{ github.ref }}".StartsWith("refs/tags/")) {
          @"
          #### Production Release
          This is an official release version (${{ env.TAG_VERSION }}) published to PyPI.

          ```
          pip install mqpy==${{ env.TAG_VERSION }}
          ```
          "@
          } else {
          @"
          #### Test/RC Version
          This is a release candidate version published to Test PyPI.

          ```
          pip install mqpy==${{ env.VERSION }}.${{ env.SUFFIX }} --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/
          ```
          "@
          })

          ### Documentation
          For complete documentation, visit our [GitHub repository](https://github.com/Joaopeuko/Mql5-Python-Integration).
          "@ | Out-File -FilePath $env:GITHUB_STEP_SUMMARY
