name: Deploy | Deploy MkDocs

on:
  workflow_dispatch:
  push:
    branches: ['*'] # <<<<<<<<< Return this to main before merging

permissions:
  contents: write

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"
      
      - name: Install the project
        run: uv sync --locked --group docs
          
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
