name: Publish distributions

on:
  push:
    branches:
      - '*'
    tags:
      - v*

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install poetry

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m poetry build
          python -m poetry publish --build --repository testpypi

          if ($env:GITHUB_REF -match '^refs/tags/v') {
            python -m poetry publish --build
          }
