name: Test | Pytest

on:
  pull_request:
  push:
    branches: ['*']

jobs:
  pytest:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov MetaTrader5
          pip install -e .
        
      - name: Run tests with coverage
        run: |
          pytest -k . --cov=mqpy --cov-append --cov-report=term-missing:skip-covered --junitxml=pytest.xml -x | tee pytest-coverage.txt
          
      - name: Generate coverage summary
        shell: pwsh
        run: |
          "## Test Coverage Summary" | Out-File -FilePath summary.md -Encoding utf8
          "```" | Out-File -FilePath summary.md -Append -Encoding utf8
          Get-Content pytest-coverage.txt | Out-File -FilePath summary.md -Append -Encoding utf8
          "```" | Out-File -FilePath summary.md -Append -Encoding utf8
          Get-Content summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8