name: Test | Pytest

on:
  pull_request:
  push:
    branches: ['*']

jobs:
  pytest:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
        
      - name: Run tests with coverage
        run: |
          pytest -k . --cov=mqpy --cov-append --cov-report=term-missing:skip-covered --junitxml=pytest.xml -x | tee pytest-coverage.txt
          
      - name: Generate coverage summary
        run: |
          echo "## Test Coverage Summary" > summary.md
          echo "```" >> summary.md
          type pytest-coverage.txt >> summary.md
          echo "```" >> summary.md

      - name: Add coverage summary to GitHub summary
        run: |
          cat summary.md >> $GITHUB_STEP_SUMMARY