name: Test MetaTrader5 Integration

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Download and Install MetaTrader 5
      run: |
        # Download MT5 setup
        Invoke-WebRequest -Uri "https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe" -OutFile mt5setup.exe
        
        # Install MT5 silently
        Start-Process -FilePath .\mt5setup.exe -ArgumentList "/auto" -Wait
        
        # Verify installation
        $mtPath = "C:\Program Files\MetaTrader 5\terminal64.exe"
        if (Test-Path $mtPath) {
          Write-Host "MetaTrader 5 installed successfully"
          Write-Host "MetaTrader 5 found at: $mtPath"
          
          # List installation directory for debugging
          Write-Host "Listing MetaTrader 5 installation directory:"
          Get-ChildItem "C:\Program Files\MetaTrader 5"
        } else {
          Write-Error "MetaTrader 5 installation failed"
          exit 1
        }
        
        # Start MT5 in portable mode and give it time to initialize
        $mtProcess = Start-Process -FilePath $mtPath -ArgumentList "/portable" -PassThru
        $processId = $mtProcess.Id
        Write-Host "Started MetaTrader 5 terminal with process ID: $processId"
        Start-Sleep -Seconds 30

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install MetaTrader5

    - name: Test MetaTrader5 connection with improved script
      run: |
        python tests/integration/test_mt5_connection.py

